spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
   #url: jdbc:mysql://172.16.0.60/sell?useUnicode=true&characterEncoding=utf-8&&useSSL=false
   # url: jdbc:mysql://192.168.199.142/sell?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    url: jdbc:mysql://172.16.0.112/sell?useUnicode=true&characterEncoding=utf-8&&useSSL=false
 #   url: jdbc:mysql://localhost:3306/sell
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell
#logging:
 # pattern:
  #  console: "%d - %msg%n"
wechat:
  mpAppId: wx76a2010f27403be7
  mpAppSecret: d33b9a13d05a9f0617c4796d9c6bba5a
